# Generated by Django 5.2 on 2025-04-28 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir el prefijo '+'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir un '+' al inicio.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
